spring:
 application:
  name: api-gateway-service
 cloud:
  gateway:
   routes:
    -id: 
     uri: lb://db-service
     predicates:
      path=/rest/db/**
  
server:
  port: 8302
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
     defaultZone: http://localhost:8300/eureka
  instance:
       hostname: localhost
     
